// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";
import * as ExpoStatusBar from "expo-status-bar";

var StatusBar = {};

function App(Props) {
  return React.createElement(ReactNative.View, {
              children: null
            }, React.createElement(ReactNative.Text, {
                  children: "Hello world!"
                }), React.createElement(ExpoStatusBar.StatusBar, {
                  style: "auto"
                }));
}

var make = App;

export {
  StatusBar ,
  make ,
  
}
/* react Not a pure module */
